### ISSUE TITLE
能否增加一个手动切换内外网的按钮？自动识别始终存在问题

### ISSUE THREAD

**Issue by muihiuwev** [blqw/nas-home-page#1]
如题。
场景一：用手机在内网访问，识别不了内网地址，又没有 alt 键可按，只能手动输入。
场景二：在内网想打开外网链接，没有快捷键，只能手动输入。

**Comment by blqw** [comment]
其实可以有个变通的方案，你在复制一个html和json 然后命名为 index-inner.html /html-inner.json
然后里面全部配置内网地址  然后再配置一个图标 叫切换内网 或者 切换外网  就可以实现
===
加代码的问题 我这边有空可以搞一下

**Comment by blqw** [comment]
好了更新了
